// buttons-poc-react/src/App.js
import '@navikt/arbeidsplassen-buttons-poc/less/index.less';

function App() {
    return (
        <div className="App">
            <button className="Button--primary">Primary</button>
            <br/>
            <br/>
            <button className="Button--secondary">Secondary</button>
            <br />
            <br />
            <button className="Button--tertiary">Tertiary</button>
            <br />
            <br />
            <button className="Button--disabled" disabled>Disabled</button>
        </div>
    );
}

export default App;

// buttons-poc-vue/src/App.vue
<template>
  <div id="app">
    <button class="Button--primary">Primary</button>
    <br>
    <br>
    <button class="Button--secondary">Secondary</button>
    <br>
    <br>
    <button class="Button--tertiary">Tertiary</button>
    <br>
    <br>
    <button class="Button--disabled" disabled>Disabled</button>
  </div>
</template>

<script>

export default {
  name: 'App',
}
</script>

<style lang="less">
@import "~@navikt/arbeidsplassen-buttons-poc/less/index";
</style>
